### ISSUE TITLE
🚀 Feature: Also comment on issues and PRs when release completes

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#128]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

One nice feature of semantic-releases was that it commented on PRs and issues. Example: https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/94#issuecomment-1349637436

> 🎉 This PR is included in version 1.3.0 🎉
> 
> The release is available on:
> 
> * [GitHub release](https://github.com/JoshuaKGoldberg/template-typescript-node-package/releases/tag/v1.3.0)
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/template-typescript-node-package/v/1.3.0)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Let's set that up with release-it (which I switched to in #110).

### Additional Info

Initially marking as blocked because I haven't looked at whether this is already supported in release-it, and/or whether anybody has asked for it yet.

**Comment by nowyDEV** [comment]
Looks like a duplicate of #230

**Comment by JoshuaKGoldberg** [comment]
Aha you're right, thanks @nowyDEV!
