### ISSUE TITLE
📝 Documentation: Not really documentation; rather feedback on using the latest and greatest

### ISSUE THREAD

**Issue by johnnyreilly** [JoshuaKGoldberg/template-typescript-node-package#147]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

When using this, I didn't know what this meant:

✔ Whether to skip calling the GitHub API (effectively making this a local-only change). · no

I still don't!  What does it mean?

The generated project still seems to be not completely initialised.  Consider the `package.json`:

```json
	"author": "Josh Goldberg <npm@joshuakgoldberg.com>",
```

Likewise, the contributors lists Josh Goldberg and not me.  

### Additional Info

Happy to provide more in depth details

**Comment by johnnyreilly** [comment]
The `.all-contributorsrc` is similarly not really updated:

```
{
  "badgeTemplate": "<img alt=\"All Contributors: <%= contributors.length %>\" src=\"https://img.shields.io/badge/all_contributors-<%= contributors.length %>-21bb42.svg\" />",
  "commit": false,
  "commitConvention": "angular",
  "contributors": [
    {
      "avatar_url": "https://avatars.githubusercontent.com/u/3335181?v=4",
      "contributions": ["tool"],
      "login": "JoshuaKGoldberg",
      "name": "Josh Goldberg",
      "profile": "http://www.joshuakgoldberg.com"
    }
  ],
  "contributorsPerLine": 7,
  "files": ["README.md"],
  "imageSize": 100,
  "projectName": "template-typescript-node-package",
  "projectOwner": "JoshuaKGoldberg",
  "repoHost": "https://github.com",
  "repoType": "github",
  "skipCi": true
}
```

BTW, as friendly as they are, I'm not in love with the contributors functionality; I find it quite noisy.  Might be nice to opt out entirely. Possibly personal preference.

**Comment by JoshuaKGoldberg** [comment]
This is great feedback, thanks @johnnyreilly. I'll file out individual issues. Keep it coming! 😄  

> When using this, I didn't know what this meant:
> ✔ Whether to skip calling the GitHub API (effectively making this a local-only change). · no

Yeah, that's not a great explanation. I'd added `--skip-api` so that when testing the setup script (e.g. in an actual end-to-end test for it, #146), there's a way to stop it from making API requests that change the repository. But you as an end user would basically never use that flag.

> The generated project still seems to be not completely initialised. Consider the package.json:

Feels like a mixture of _bug_ and _feature request_. It should ideally replace that `author` with the GitHub auth of whoever is running the script. Maybe even the end-to-end test script should verify that the string `josh` is nowhere in the repository after switching to test values...

> Likewise, the contributors lists Josh Goldberg and not me.
> ...
> The .all-contributorsrc is similarly not really updated:

I am slightly egotistically keeping myself in that list for `"tool"` because hey, it's my tooling that set up the package! But similar to the `author` portion, agreed, you the setup user should be added to it. 

> Might be nice to opt out entirely. 

Heh, yeah. I can see it being especially noisy if used in single-person personal projects or even closed source projects... I'm personally not motivated to add the requisite logic to be able to turn different areas of integration on or off. But if you have ideas, I'd be up for receiving an issue and ponder some more.

---

Btw, @allcontributors add @johnnyreilly for bug, ideas, promotion. I'm trying to get better at remembering to do this - these all should have been done a while ago. 😄

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @johnnyreilly for bug, ideas, promotion.

**Comment by johnnyreilly** [comment]
I need to discover what @allcontributors is! But not right now.  Another one: the initialised README is also kind of incomplete; still lists the template repo stuff / old contributors etc

```mdx
<h1 align="center">Remark Cloudinary Docusaurus plugin</h1>

<p align="center">Cloudinary offers an image CDN which can improve performance of your site. This plugin allows Docusaurus to use Cloudinary to serve optimised images.</p>

<p align="center">
	<a href="#contributors" target="_blank">
<!-- prettier-ignore-start -->
<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
<img alt="All Contributors: 4" src="https://img.shields.io/badge/all_contributors-4-21bb42.svg" />
<!-- ALL-CONTRIBUTORS-BADGE:END -->
<!-- prettier-ignore-end -->
	</a>
	<a href="https://codecov.io/gh/johnnyreilly/remark-cloudinary-docusaurus" target="_blank">
		<img alt="Codecov Test Coverage" src="https://codecov.io/gh/JoshuaKGoldberg/template-typescript-node-package/branch/main/graph/badge.svg?token=eVIFY4MhfQ"/>
	</a>
	<a href="https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/main/.github/CODE_OF_CONDUCT.md" target="_blank">
		<img alt="Contributor Covenant" src="https://img.shields.io/badge/code_of_conduct-enforced-21bb42" />
	</a>
	<a href="https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/main/LICENSE.md" target="_blank">
	    <img alt="License: MIT" src="https://img.shields.io/github/license/JoshuaKGoldberg/template-typescript-node-package?color=21bb42">
    </a>
	<a href="https://github.com/sponsors/JoshuaKGoldberg" target="_blank">
    	<img alt="Sponsor: On GitHub" src="https://img.shields.io/badge/sponsor-on_github-21bb42.svg" />
    </a>
	<img alt="Style: Prettier" src="https://img.shields.io/badge/style-prettier-21bb42.svg" />
    <img alt="TypeScript: Strict" src="https://img.shields.io/badge/typescript-strict-21bb42.svg" />
</p>

## Usage

```shell
npm i template-typescript-node-package
```

```ts
import { greet } from "template-typescript-node-package";

greet("Hello, world!");
```

## Development

See [`.github/CONTRIBUTING.md`](./.github/CONTRIBUTING.md).
Thanks! 💖

## Contributors







<table>
  <tbody>
    <tr>
      <td align="center"><a href="http://www.joshuakgoldberg.com"><img src="https://avatars.githubusercontent.com/u/3335181?v=4?s=100" width="100px;" alt="Josh Goldberg"/><br /><sub><b>Josh Goldberg</b></sub></a><br /><a href="https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=author%3AJoshuaKGoldberg" title="Bug reports">🐛</a> <a href="https://github.com/JoshuaKGoldberg/template-typescript-node-package/commits?author=JoshuaKGoldberg" title="Code">💻</a> <a href="#content-JoshuaKGoldberg" title="Content">🖋</a> <a href="#example-JoshuaKGoldberg" title="Examples">💡</a> <a href="#ideas-JoshuaKGoldberg" title="Ideas, Planning, & Feedback">🤔</a> <a href="#infra-JoshuaKGoldberg" title="Infrastructure (Hosting, Build-Tools, etc)">🚇</a> <a href="#maintenance-JoshuaKGoldberg" title="Maintenance">🚧</a> <a href="#platform-JoshuaKGoldberg" title="Packaging/porting to new platform">📦</a> <a href="#projectManagement-JoshuaKGoldberg" title="Project Management">📆</a> <a href="https://github.com/JoshuaKGoldberg/template-typescript-node-package/pulls?q=is%3Apr+reviewed-by%3AJoshuaKGoldberg" title="Reviewed Pull Requests">👀</a> <a href="#security-JoshuaKGoldberg" title="Security">🛡️</a> <a href="#tool-JoshuaKGoldberg" title="Tools">🔧</a> <a href="https://github.com/JoshuaKGoldberg/template-typescript-node-package/commits?author=JoshuaKGoldberg" title="Tests">⚠️</a></td>
      <td align="center"><a href="https://sinchang.me"><img src="https://avatars.githubusercontent.com/u/3297859?v=4?s=100" width="100px;" alt="Jeff Wen"/><br /><sub><b>Jeff Wen</b></sub></a><br /><a href="#tool-sinchang" title="Tools">🔧</a></td>
      <td align="center"><a href="https://paulisaweso.me/"><img src="https://avatars.githubusercontent.com/u/6335792?v=4?s=100" width="100px;" alt="Paul Esch-Laurent"/><br /><sub><b>Paul Esch-Laurent</b></sub></a><br /><a href="#tool-Pinjasaur" title="Tools">🔧</a></td>
      <td align="center"><a href="https://github.com/NazCodeland"><img src="https://avatars.githubusercontent.com/u/113494366?v=4?s=100" width="100px;" alt="NazCodeland"/><br /><sub><b>NazCodeland</b></sub></a><br /><a href="#tool-NazCodeland" title="Tools">🔧</a></td>
    </tr>
  </tbody>
</table>











> 💙 This package is based on [@JoshuaKGoldberg](https://github.com/JoshuaKGoldberg)'s [template-typescript-node-package](https://github.com/JoshuaKGoldberg/template-typescript-node-package).


	
	
	> 💙 This package is based on [@JoshuaKGoldberg](https://github.com/JoshuaKGoldberg)'s [template-typescript-node-package](https://github.com/JoshuaKGoldberg/template-typescript-node-package).
```

**Comment by johnnyreilly** [comment]
Ignore me @allcontibutors. This is going to screw you up too but that's life :wink: 

> I am slightly egotistically keeping myself in that list for "tool" because hey, it's my tooling that set up the package! But similar to the author portion, agreed, you the setup user should be added to it.

I understand that, but I suspect users and potential users may take the view "look, the electricity company is in some way a contributor to this, in that without electricity, this wouldn't be here.  But it's not relevant - I don't want it".  Harsh, but I quite possibly a common sentiment.

**Comment by johnnyreilly** [comment]
Oh and a question:

> ACCESS_TOKEN: A [GitHub PAT](https://github.com/settings/tokens/new) with repo permissions

I've an idea there's a built in token that GitHub Actions can access - could that be used instead?

**Comment by johnnyreilly** [comment]
![image](https://user-images.githubusercontent.com/1010525/209444044-56c51a04-df10-4066-b5d5-e4ce50307e67.png)

github actions also not updated by the looks

**Comment by johnnyreilly** [comment]
Dammit - it published src and not lib

![image](https://user-images.githubusercontent.com/1010525/209444640-af547b67-2ce4-4311-9527-2797da185fce.png)

https://www.npmjs.com/package/remark-cloudinary-docusaurus?activeTab=explore

**Comment by JoshuaKGoldberg** [comment]
On the bright side, this is the first time I've seen `activeTab=explore` in action on npmjs.com! 🙃

**Comment by johnnyreilly** [comment]
Same!

**Comment by johnnyreilly** [comment]
Probably going to call it for now, but somehow there's a way to make (I guess) release-it use `lib` instead of `src` when it publishes.  Don't know what though

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @johnnyreilly for bug

**Comment by johnnyreilly** [comment]
Probably something to do with this: https://github.com/release-it/release-it/blob/HEAD/docs/npm.md#publish-path

But it looks like release-it may not have run the build prior to it perhaps?

**Comment by johnnyreilly** [comment]
trying this: https://github.com/johnnyreilly/remark-cloudinary-docusaurus/commit/a2bebf2bc5f4eed62a47f8f83e1bbd07c91e983e

**Comment by johnnyreilly** [comment]
that worked I think

**Comment by JoshuaKGoldberg** [comment]
Amazing! And yeah it makes a lot of sense. Up for sending a PR? You've already contributed so much to this repo, might as well get in the code history too 😄

**Comment by johnnyreilly** [comment]
yeah sure - probably after Christmas.  Merry Christmas Josh!

**Comment by JoshuaKGoldberg** [comment]
Merry Christmas!

![Joe Pesci from Home Alone saying "Merry Christmas", smiling, with a gold tooth shining](https://user-images.githubusercontent.com/3335181/209445145-b9868d71-8175-4d5c-b663-cab5a1453fdf.gif)

**Comment by johnnyreilly** [comment]
Haha - I can't work out if there's a latent threat in that GiF 😅

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @johnnyreilly for maintenance
