### ISSUE TITLE
🛠 Tooling: Investigate simplifying setup to not need ACCESS_TOKEN

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#159]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

From https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/147#issuecomment-1364487493: `${{ secrets.GITHUB_TOKEN }}` should already exist. Is asking users to create an `ACCESS_TOKEN` `PAT` & using it in `release.yml` unnecessary work?

It'd be great if we can use the built-in token instead, so users don't have to make a new one.

### Additional Info

For context, it's used in `release.yml` right now to call to the GitHub API for toggling branch protections before & after package releasing.

https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/8c5722e7ccc0fbbec6367bd0cecfc51031c361e1/.github/workflows/release.yml#L42

**Comment by JoshuaKGoldberg** [comment]
@johnnyreilly - do you want to take this one? 😄

**Comment by johnnyreilly** [comment]
Haha - maybe!

**Comment by JoshuaKGoldberg** [comment]
I tried setting up a new repo without `ACCESS_TOKEN` and alas, `GH_TOKEN` doesn't seem to work. 

https://github.com/JoshuaKGoldberg/should-semantic-release/commit/154b497733da1e0b95dabf81145be582f988f4ab

https://github.com/JoshuaKGoldberg/should-semantic-release/actions/runs/3943261197/jobs/6747896171

```plaintext
Run actions/github-script@v6.3.3
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v6.3.3/dist/index.js:6172:[21](https://github.com/JoshuaKGoldberg/should-semantic-release/actions/runs/3943261197/jobs/6747896171#step:8:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6.3.3/dist/index.js:13356:16), <anonymous>:4:3)
```

😞 

Let me know if I'm wrong here? Until then, I'll close this out. Thanks for reporting!
