### ISSUE TITLE
🚀 Feature: Offer to create a repository in setup if it doesn't yet exist

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#183]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

When running setup (`pnpm setup`) on a new project that doesn't yet have a Git repo, this error happens:

```plaintext
Hydrating initial repository settings...

Hydrating branch protection settings...
/Users/josh/repos/should-skip-semantic-release/node_modules/.pnpm/@octokit+request@6.2.2/node_modules/@octokit/request/dist-node/index.js:88
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Not Found
    at /Users/josh/repos/should-skip-semantic-release/node_modules/.pnpm/@octokit+request@6.2.2/node_modules/@octokit/request/dist-node/index.js:88:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Job.doExecute (/Users/josh/repos/should-skip-semantic-release/node_modules/.pnpm/bottleneck@2.19.5/node_modules/bottleneck/light.js:405:18) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/JoshuaKGoldberg/should-skip-semantic-release',
    status: 404,
...
```

The setup script should use the GitHub API to create a new repository for the specified owner under the given kebab-case name. ✨ 

### Additional Info

Steps to repro:

1. Copy the template package to a new directory locally. E.g.:
    ```shell
    cp -r path/to/template-typescript-node-package some/new/path
    cd some/new/path
    rm -rf node_modules
    pnpm install
    ```
2. Run setup (`pnpm run setup`), filling in any info and having it call to the GitHub API

**Comment by TAKANOME-DEV** [comment]
I'm unable to reproduce the same error, seems it was trying to create a repo or...?
```sh
Welcome to the template-typescript-node-package package setup!
This setup script will hydrate your repository based on your provided settings.

✔ What will the kebab-case name of the repository be? · test-node-template
✔ What will the Title Case title of the repository be? · TestNodeTemplate
✔ What owner or user will the repository be under? · TAKANOME-DEV
✔ How would you describe the new package? · 
✔ Whether to skip calling the GitHub API (effectively making this a local-only change). · 

Hydrating package metadata locally...
✔️ Done.

Clearing CHANGELOG.md...
✔️ Done.

Deleting local git tags...
✔️ Done.
✔️ Done.

Checking gh auth status...
✔️ Done.

Hydrating repository labels...
Error: HTTP 404: Not Found (https://api.github.com/repos/JoshuaKGoldberg/template-typescript-node-package/labels/area:%20documentation)
    at file:///home/takanome_dev/Projects/OpenSource/JoshuaKGoldberg/test-bug/script/setup.js:193:11
    exit code: 1
    at ChildProcess.<anonymous> (file:///home/takanome_dev/.npm/_npx/721a1717bb84573e/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)

Removing devDependency packages only used for setup...
✔️ Done.

Looks like there was a problem. Correct it and try again? 😕
```
### Note
- I was confused by this `Whether to skip calling the GitHub API (effectively making this a local-only change).`
  I didn't know what to respond and there is no hint
- The last message: `Looks like there was a problem. Correct it and try again? 😕`
  Maybe we should change the `correct it` part with something else :sweat_smile:

**Comment by JoshuaKGoldberg** [comment]
Heh, glad to see it's not quite so crash-y now! But this blob of error stack isn't what people would want to see:

```plaintext
Hydrating repository labels...
Error: HTTP 404: Not Found (https://api.github.com/repos/JoshuaKGoldberg/template-typescript-node-package/labels/area:%20documentation)
    at file:///home/takanome_dev/Projects/OpenSource/JoshuaKGoldberg/test-bug/script/setup.js:193:11
    exit code: 1
    at ChildProcess.<anonymous> (file:///home/takanome_dev/.npm/_npx/721a1717bb84573e/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
```

The error in particular is curious. `Error: HTTP 404: Not Found (https://api.github.com/repos/JoshuaKGoldberg/template-typescript-node-package/labels/area:%20documentation)` - why is it calling to `JoshuaKGoldberg/template-typescript-node-package`? Shouldn't it be asking your own repo? This might be a separate bug.

Either way, I think this feature request still stands - that making a new repo if one doesn't exist would be nice.

> I was confused by this `Whether to skip calling the GitHub API (effectively making this a local-only change).`
> I didn't know what to respond and there is no hint

Yeah, that's not great a great dev experience bit right now. You did the right thing by ignoring. The fix should be fairly straightforward if you're interested! #184

> The last message: `Looks like there was a problem. Correct it and try again? 😕`
> Maybe we should change the `correct it` part with something else :sweat_smile: 

Got any suggestions?

**Comment by TAKANOME-DEV** [comment]
> Why is it calling to `JoshuaKGoldberg/template-typescript-node-package`? Shouldn't it be asking your own repo? This might be a separate bug.
> 
Or maybe I did something wrong :thinking: I will retry it and report back if it's the same
> Either way, I think this feature request still stands - that making a new repo if one doesn't exist would be nice.
> 
Yeah, definitely. I'll look into it
> The fix should be fairly straightforward if you're interested! #184
> 
Sure,will take that :+1: 
> > Maybe we should change the `correct it` part with something else sweat_smile
> 
> Got any suggestions?
>
What do you think of:
"Sorry, there was an error. Please check your inputs and try again. If you need help, reach out to us."

**Comment by JoshuaKGoldberg** [comment]
> "Sorry, there was an error. Please check your inputs and try again. If you need help, reach out to us."

🔥 Looks great! A couple of suggestions:

* Maybe replace _"Sorry"_ with _"Huh"_? Nothing wrong with apologizing, but I think so many apps say "sorry" it's kind of lost meaning / feels generic to me.
* Maybe something more specific than _"reach out to us"_ - it might not be clear how to do that. Maybe link to this GitHub repo?

**Comment by TAKANOME-DEV** [comment]
> Maybe replace _"Sorry"_ with _"Huh"_? Nothing wrong with apologizing, but I think so many apps say "sorry" it's kind of lost meaning / feels generic to me.
> 
Agree
> Maybe something more specific than _"reach out to us"_ - it might not be clear how to do that. Maybe link to this GitHub repo?
>
Yeah, forgot about the link. And maybe the link can be a new bug report issue :thinking:

**Comment by JoshuaKGoldberg** [comment]
#398 raises a good point: what if the repository name was just mistyped? In this case I think the script should offer the person to try again or create a new repository for them.

Removing the `good first issue` label as this is a bit more complex now.
