### ISSUE TITLE
🚀 Feature: Setup script should hide the --skip-api option (not prompt for it)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#184]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, when you run `pnpm setup` with no arguments, it brings you through a list of options:

```plaintext
✔ What will the kebab-case name of the repository be? · should-skip-semantic-release
✔ What will the Title Case title of the repository be? · Should Skip Semantic Release
✔ What owner or user will the repository be under? · JoshuaKGoldberg
✔ How would you describe the new package? · Small utility to check whether a semantic release should be skipped for a commit.
✔ Whether to skip calling the GitHub API (effectively making this a local-only change). · 
```

That last one, known internally as `--skip-api` is pretty useless to most users - and confusing to anybody who isn't super deeply contextualized in this repo. `--skip-api` is really just for testing during development. I think the option shouldn't even be shown in the CLI. It should just be mentioned in the README.md.

**Comment by TAKANOME-DEV** [comment]
I was confused by the last prompt when I tried running the setup :sweat_smile:  
Let me try fixing this

**Comment by TAKANOME-DEV** [comment]
Since `--skip-api` is going to be hidden by default, I assume it will be renamed to something else that will call the github API if include when running `pnpm setup`.

Maybe something like `--hydrate` :thinking: I don't know :sweat_smile: 

What's your take @JoshuaKGoldberg ?

**Comment by JoshuaKGoldberg** [comment]
Err, why rename it? What's off about calling it `--skip-api` as a hidden option?

**Comment by TAKANOME-DEV** [comment]
I think it's a bit confusing to have a flag called `--skip-api` but it actually calls the github API.
But if you think it's fine, I'm fine with it :ok_hand:

**Comment by JoshuaKGoldberg** [comment]
When `--skip-api` is truthy, we _don't_ call the GitHub API.
