### ISSUE TITLE
🛠 Tooling: Add a lint rule enforcing a space after }

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#231]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I sometimes see code like that has a `}` not followed by a blank line and personally find it hard to read:

```ts
export function apple() {
	return "apple";
}
export function bananaOrCherry(condition: boolean) {
	if (condition) {
		return "banana";
	}
	console.log("cherry");
	return;
}
```

Normally I don't mess with lint rules that touch formatting. But Prettier won't touch this case, and it's irksome to me. Let's set the ESLint configuration in this template to require a newline after `}`.

```ts
export function apple() {
	return "apple";
}

export function bananaOrCherry(condition: boolean) {
	if (condition) {
		return "banana";
	}

	console.log("cherry");
	return;
}
```

**Comment by kou333** [comment]
Iam a beginner and trying to find the solution for this issue and  found out that To configure ESLint to require a newline after }, you can add the object-curly-spacing rule and set the always option to true. Here's an example configuration in a .eslintrcfile.

{
  "rules": {
    "object-curly-spacing": ["Warning", "always"]
  }
}

we can give a warning message so that the issue is solved is it correct?

**Comment by JoshuaKGoldberg** [comment]
@kou333 hello and welcome!

> object-curly-spacing rule

Not quite. The [`object-curly-spacing` rule](https://eslint.org/docs/latest/rules/object-curly-spacing) applies to _spacing inside object brackets_. It might be configured to suggest something like:

```diff
- const value = {happy: true};
+ const value = { happy: true };
```

I'm looking for something that applies to a _newline after a closing bracket_. See the top post in this issue for what that would look like

> we can give a warning message so that the issue is solved is it correct?

When we do find a rule, I'll want it to be configured as `"error"`, not `"warn"` (see the [ESLint _Configure Rules_ docs](https://eslint.org/docs/latest/use/configure/rules)). In my experience, warnings tend to get ignored over time. Only blocking errors really prevent people from checking in violating code.

---

Aside: your posts will be easier to read if you format them nicely with [GitHub Flavored Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). See [this GFM cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) for a nice quick reference. Cheers!
