### ISSUE TITLE
🛠 Tooling: Enforce .js extensions for imports

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#233]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, this repo writes `import` statements with explicit `.js` extensions for relative file paths:

```ts
import { greet } from "./greet.js";
```

It does so because the output ESM (ECMAScript Modules) `.js` files need that explicit `.js` extension. The ESM import algorithm doesn't allow omitting it. You can read more at https://www.typescriptlang.org/docs/handbook/esm-node.html.

I'd like some sort of check in this repo to make sure that if you write an `export` or `import` or `export` statement in code, it uses the explicit extension. Because otherwise there's nothing stopping folks from checking this in and then causing package build breaks like I did! 

* Bug: https://github.com/JoshuaKGoldberg/ts-api-utils/issues/35
* Fix: https://github.com/JoshuaKGoldberg/ts-api-utils/pull/36

### Additional Info

It looks like this rule is what I'm looking for? https://github.com/import-js/eslint-plugin-import/blob/d5fc8b670dc8e6903dbb7b0894452f60c03089f5/docs/rules/extensions.md

**Comment by RebeccaStevens** [comment]
Would it not be better to just also bundle the esm? It seems kind of strange to me that only the csj is bundled. Would we not want both systems to benefit from it?

The build scripts could be defined like this:

```
"scripts": {
  "build": "pnpm build:esm && pnpm build:cjs",
  "build:cjs": "tsup src/index.ts --format cjs --outDir lib --dts",
  "build:esm": "tsup src/index.ts --format esm --outDir lib --dts",
}
```
