### ISSUE TITLE
🛠 Tooling: Bring in workflow permissions fixes from ts-api-utils

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#241]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Shoutout @RebeccaStevens for comments in https://github.com/JoshuaKGoldberg/ts-api-utils/issues/30 -> sending https://github.com/JoshuaKGoldberg/ts-api-utils/pull/71! 🙌  We'll want those fixes in this repo too.

**Comment by TAKANOME-DEV** [comment]
Seems like a good first issue for me 🙂
