### ISSUE TITLE
🛠 Tooling: Should set eslint.probe in ESLint settings to include .json, etc.

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#244]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

TIL that the VS Code ESLint extension will stay silent _unless_ a file in one of the following default language formats is found: `"javascript", "javascriptreact", "typescript", "typescriptreact", "html", "vue", "markdown"]`. https://github.com/microsoft/vscode-eslint/blob/560df864580a9381d84b2f1e408f46f6600fda48/README.md#settings-options

To repro:

1. Open the repo folder in VS Code without opening any files by default
2. Open any `.json` and/or `.jsonc` file(s)

VS Code will give a little prompt saying:

```plaintext
ESLint is not running. By default only TypeScript and JavaScript files are validated. If you want to validate other file types please specify them in the 'eslint.probe' setting.
```

This repo configures linting for other extensions such as `.json`, `.jsonc`, and `.md`. We should update the `eslint.probe` setting in `.vscode/settings.json` to include the corresponding VS Code language identifiers.

Note that an _extension_ (e.g. `.json`) is not the same as a _language identifier_ (e.g. `"json"`). https://code.visualstudio.com/docs/languages/identifiers 

### Additional Info

![Screenshot of a VS Code prompt with the aforementioned text](https://user-images.githubusercontent.com/3335181/219932666-09fe8170-307f-43ad-8e49-83836b4ba0f4.png)

**Comment by the-lazy-learner** [comment]
Could I try an attempt at trying to solve this?

**Comment by JoshuaKGoldberg** [comment]
@the-lazy-learner absolutely, please do! 🙌

**Comment by the-lazy-learner** [comment]
Please review PR #267

**Comment by the-lazy-learner** [comment]
Unfortunately, had to delay because of health issues, please check now if it looks ok

**Comment by JoshuaKGoldberg** [comment]
❤️ hope you're feeling better @the-lazy-learner!

Btw, you don't need to explicitly ask for re-review in comments. I updated the development docs to mention this: https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/314 _(it doesn't bother me, just wanted to save you some time 😄)_
