### ISSUE TITLE
🛠 Tooling: Add alphabetical sorting to yaml files?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#258]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

#50 and #53 added alphabetical sorting to keys in a couple other forms of code. But right now nothing verifies that `.yaml`/`.yml` files are in alphabetical order. Which, for the sake of keeping things organized & easier to find things in, would be really nice IMO.

### Additional Info

I don't know what the best tool would be - an ESLint plugin? A standalone YAML linter? Investigation required! Before settling on one, I'd like to see what the options are, and what they support.

**Comment by nowyDEV** [comment]
I've done some research and it looks like ESLint plugin is the way to go.

List of possible tools:
- https://github.com/ddebin/yaml-sort
  - JS-based (npm package)
  - Has formatter & checker

- https://mikefarah.gitbook.io/yq/operators/sort-keys
  - Future-rich yaml processor
  - Has dedicated github action
  - It would need to be run locally inside Docker (no npm package)

- https://github.com/ota-meshi/eslint-plugin-yml
  - Works by providing AST and source code text to ESLint
  - Has a lot of additional rules that could help with consistent style of our YAML files and save us from errors
  - Includes rules for alphabetic sorting
    - https://ota-meshi.github.io/eslint-plugin-yml/rules/sort-keys.html
    - https://ota-meshi.github.io/eslint-plugin-yml/rules/sort-sequence-values.html

**Comment by JoshuaKGoldberg** [comment]
Awesome, thanks for the investigation @nowyDEV! Agreed with your conclusion 😄. Since ESLint is already setup for `.json(c)` and `.md` files and `eslint-plugin-yml` is looking nicely supported, I'm very into using it.

Accepting PRs! 🚀
