### ISSUE TITLE
My version

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/template-typescript-node-package#265]
I thought I'd make my own template repo (pretty much just for personal use) inspired by this one.

I just opening this issue to let you know in case you wanted to check it out: https://github.com/RebeccaStevens/template-typescript-node-package/

**Comment by JoshuaKGoldberg** [comment]
Aha awesome! I see you have some good tools in there, including Ava and Rollup. Nice.

Are there any things you'd suggest be brought into this package?

**Comment by RebeccaStevens** [comment]
Nothing in particular. They two are pretty similar. I do have a few extra workflows though if you want to take a look.

One thing that it might be worth bringing over here is how I set up the release workflow to require other workflows to passes.

**Comment by JoshuaKGoldberg** [comment]
Closing for housekeeping purposes - thanks for the reference!
