### ISSUE TITLE
🛠 Tooling: ESLint isn't enforcing alphabetical sort in (dot) .json files

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#279]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

See https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/268/files#diff-5ab963cb08e89b9caebf40ea2bfb8880cfec70dfab12e3707b29e7e7e0e6defcR9:

```json
{
	"release": true,
	"releaseName": "v${version}",
	"autoGenerate": true
}
```

This repo's ESLint config _should_ be targeting all `.json(c)` files to have alphabetical sorting in their objects:

https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/9550acb96dc1d554cc26af6ee69c171f6ecbf4ba/.eslintrc.cjs#L34-L42

...but that isn't getting applied to `.release-it.json`. Why not? This is a tooling bug and should be fixed.

**Comment by nowyDEV** [comment]
This was resolved in https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/285/commits/88a560891a9962e842cfe9c9484e27b291968d7e#diff-5ab963cb08e89b9caebf40ea2bfb8880cfec70dfab12e3707b29e7e7e0e6defc

**Comment by JoshuaKGoldberg** [comment]
_heck yes_
