### ISSUE TITLE
🛠 Tooling: Investigate using changesets instead of release-it

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#297]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

https://github.com/changesets/changesets looks pretty snazzy. It was suggested by ParasocialFix in my Twitch stream today. I like how it sets up a lot of stuff (changelog, releases in a GitHub Action, ...) for you. Maybe the right thing to move to?

### Additional Info

@Andarist also contributes, which is a big +1 for me 😄

**Comment by Andarist** [comment]
Happy to give you some intro to Changesets so you could just by yourself if that's a good fit.

**Comment by JoshuaKGoldberg** [comment]
Ok following up on this - I think the having to add an extra patch file is a blocker. Changesets is excellent and I'd definitely want to use it on a "real" (not-small/midsized) project. But this template is really tailored to smaller/midsized apps that don't want to have another layer of tooling to work with.

From another direction: this template is hard enough for newcomers to work with, given all the linting & such. They'd have an even harder time having to work with changesets.

Per https://github.com/changesets/changesets/issues/665#issuecomment-1478887484: if Changesets could support conventional commits -first-party or plugin- then I'd hop on it _fast_.

Thanks for the walkthrough & help @Andarist! ❤️
