### ISSUE TITLE
📝 Documentation: Setup instructions for a new repo

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#3]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue+label%3A%22area%3A+documentation%22) and found none that matched my issue.

### Overview

I'll want to document what to do to take this template & make a new repo out of it.

### Additional Info

At the very least:

* Find-and-replace `template-typescript-node-package` to the new name
* Fill out TODO in `.md` files
* Empty out `src/`
* Create a new package-specific publish token and set it as the `NPM_TOKEN` env variable in settings
* Make sure `GH_TOKEN` is available on your account in CI
* Set up required CI jobs
* Go through GitHub settings in general:
  * Disable Wikis
  * Enable Sponsorships
  * Uncheck _Allow merge commits_ and _Allow rebase merging_
  * Uncheck _Projects_
  * Check _Always suggest updating pull request branches_
  * Check _Allow auto-merge_
  * Check _Automatically delete head branches_
  * Check _Limit how many branches and tags can be updated in a single push_
* Clearing out the all-contributors badge & table
* Set version to something like `0.1.0` or `0.0.1`

**Comment by JoshuaKGoldberg** [comment]
https://github.com/johnnyreilly/easyauth-deeplink/pull/1 is an example of where these would have been helpful. cc @johnnyreilly

**Comment by johnnyreilly** [comment]
Looks like the `dist` folder has been regenerated on publish - is that intentional?  It's in `.gitignore`

**Comment by johnnyreilly** [comment]
also when it publishes it goes straight to 1.0.0 - regardless of what you've set in package.json.  May just be a side effect of using semantic commits

**Comment by JoshuaKGoldberg** [comment]
I think it is, yeah. I'd consider that a bug.

**Comment by johnnyreilly** [comment]
In other news my son just looked over my shoulder and decided you had a cool name.  He also checked whether it was real or whether you'd invented it.

**Comment by JoshuaKGoldberg** [comment]
Oh _heck yes_. I'll forward the positive feedback along to the parents!

**Comment by johnnyreilly** [comment]
May have found another issue - when I protected my main branch I found I couldn't release anymore (possibly because it's trying to update the main branch with dist?)

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/1010525/205481127-5460f1f5-137c-4b3c-b461-da628471078b.png">

**Comment by johnnyreilly** [comment]
I think there's probably more too it - it wouldn't allow me to have status checks protection in place either.  Have removed all protection on main branch
