### ISSUE TITLE
🛠 Tooling: Add code coverage reporting

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#31]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue+label%3A%22area%3A+tooling%22) and found none that matched my issue.

### Overview

Codecov, Code Climate, Coveralls - all options!

### Additional Info

I don't want to bake in minimum coverage %s to this template (that's a bit much for a general-purpose template). But at least reporting changes is good.

**Comment by Kingris9090** [comment]
> Owner
