### ISSUE TITLE
🛠 Tooling: Consider execa vs zx

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#340]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Forking from @navin-moorthy's https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/334#issuecomment-1490392645: 

> What's your thought on using `execa` [release v7.1.0](https://github.com/sindresorhus/execa/releases/tag/v7.1.0) with script interface ?
> 
> [`execa` vs `zx` comparsion](https://github.com/sindresorhus/execa/blob/main/docs/scripts.md?rgh-link-date=2023-03-30T14%3A19%3A35Z).

### Additional Info

I'm not tied to either tool. This repo already uses zx right now and it works great. So I'd need to see some strong reason to use execa instead to switch. Is there a good motivation,  @navin-moorthy? 

_(personal familiarity notwithstanding 😄)_

**Comment by navin-moorthy** [comment]
Here is the comparison between `execa` and `zx`,

https://github.com/sindresorhus/execa/blob/b44d4066aebd2db0c7864936e710b9fa6f5ab9d2/docs/scripts.md?plain=1#L43-L69

No strong opinion, just considering these advantages.

**Comment by JoshuaKGoldberg** [comment]
Ok @navin-moorthy I've thought about this a bit and think you're very right to suggest `execa` 😄. Having users `import { $ } from "execa";` means scripts can be executed by `node` normally - as opposed to `zx`, which requires using `zx` to run them. That alone is enough reason for me!

Marking as accepting PRs - are you interested in making the switch? No worries if not, just making sure you can get first dibs at the opportunity if you have the time! 😁

**Comment by navin-moorthy** [comment]
Yes, I can raise a PR for this.
