### ISSUE TITLE
🚀 Feature: Add label-syncer action to sync labels

### ISSUE THREAD

**Issue by navin-moorthy** [JoshuaKGoldberg/template-typescript-node-package#342]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I recently came across [RebeccaStevens](https://github.com/RebeccaStevens) [template-typescript-node-package repo](https://github.com/RebeccaStevens/template-typescript-node-package).

This repo uses https://github.com/micnncim/action-label-syncer and just provide labels in the path [`.github/labels.yml`](https://github.com/RebeccaStevens/eslint-config-rebeccastevens/blob/main/.github/labels.yml).

This will separate setting up the label in `pnpm run setup`.

### Additional Info

References: https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/262, https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/331

**Comment by JoshuaKGoldberg** [comment]
You know, this is a good idea, but I'm reluctant to add noise to a repo after it's been set up. Repos will have to now set up a `labels.yml` file. There are already a lot of config files in the repos... then again, I do see the advantage of not having to set it up in the script, and making it easier to update later on.

Let's leave this open for a bit and see if more people have opinions?

**Comment by JoshuaKGoldberg** [comment]
Ok I've been poking around other repositories and haven't seen label syncing in use much. I'm going to go ahead and close this as it seems like a not-super-commonly-used thing. I personally am not excited about its benefits to warrant the extra file + workflows in a repo.

Thanks for suggesting though! ❤️
