### ISSUE TITLE
🛠 Tooling: Offer to git reset/restore on error in setup script

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#353]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Separating out of @navin-moorthy's #349: if `pnpm run setup` -> [`script/setup.js`](https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/1e29b61bd538f4130231ca58e9999b7a07d14c6b/script/setup.js) throws an error, it might be useful to reset the repository afterward. `git restore .` should do the trick.

Let's add a Clack prompt in the case of a failure. By default the script shouldn't restore, as if the setup mostly worked that alone might be enough for the user.

### Additional Info

See https://github.com/JoshuaKGoldberg/template-typescript-node-package/tree/1e29b61bd538f4130231ca58e9999b7a07d14c6b#setup for explanation of the setup script.

**Comment by navin-moorthy** [comment]
I will raise a PR for this after the approval of #356
