### ISSUE TITLE
🛠 Tooling: Find a way around using shell: true in setup-test-e2e.js

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#357]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

See discussion in https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/349/files#r1156109852. We use `shell: true` in a `grep` command in `script/setup-test-e2e.js` because without it, depending on the person running the script, the command either hangs or fails with `no such file or directory`. Fun!

https://github.com/sindresorhus/execa/blob/main/readme.md#shell recommends against using `shell: true`. So it'd be nice if someone could figure out how to get the `setup-test-e2e.js` file working.

### Additional Info

`script/setup-test-e2e.js` is the file run to test that `script/setup.js` works as expected. I generally run the file locally with `pnpm run setup:test`. See https://github.com/JoshuaKGoldberg/template-typescript-node-package#setup for an explanation of why we have a setup command.

**Comment by navin-moorthy** [comment]
Created an issue in `execa` for a solution - https://github.com/sindresorhus/execa/issues/555

**Comment by navin-moorthy** [comment]
This works without `{shell: true}`
```js
const files = await globby(["*.*", "**/*.*"], {
	gitignore: true,
	ignoreFiles: ["script/setup.js", "script/setup-test-e2e.js"],
});

for (const search of [
	`/JoshuaKGoldberg/`,
	"template-typescript-node-package",
]) {
	const { stdout } = await $`grep -i ${search} ${files}`;
	assert.equal(
		stdout,
		`README.md:> 💙 This package is based on [@JoshuaKGoldberg](https://github.com/JoshuaKGoldberg)'s [template-typescript-node-package](https://github.com/JoshuaKGoldberg/template-typescript-node-package).`
	);
}
```


Reference: https://github.com/sindresorhus/execa/issues/555
