### ISSUE TITLE
📝 Documentation: Improve template setup instructions for private repos

### ISSUE THREAD

**Issue by RNR1** [JoshuaKGoldberg/template-typescript-node-package#398]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I have been trying to use this node template, and it took me a few tries until I got the setup right.
I believe the setup docs could be more accurate.

### Additional Info

here are the issues I ran into:
- I need to be logged in to GitHub CLI; it was mentioned, but maybe it needs more highlighting.
- I have to use the same repo name that I used on GitHub, and without .git in the end (as the CLI suggests)
- If my repository is private on GitHub, I have to be a Pro user or make it public

Failing in these steps required me to git revert changes and start over.

## Screenshots

![not-logged-in](https://user-images.githubusercontent.com/45559220/236045166-2637397a-8649-405a-8ba9-190d26ad2b82.jpg)

<img width="503" alt="not-found" src="https://user-images.githubusercontent.com/45559220/236044240-9f2744cc-f6c7-4bc0-9cef-5ad23b1fc3ef.png">

<img width="797" alt="public-or-pro" src="https://user-images.githubusercontent.com/45559220/236044245-6f489e22-cfc9-4f14-8de8-5aba668946bd.png">

**Comment by JoshuaKGoldberg** [comment]
> I need to be logged in to GitHub CLI; it was mentioned, but maybe it needs more highlighting.

Agreed, good point. #400 ✨ 

> I have to use the same repo name that I used on GitHub, and without .git in the end (as the CLI suggests)

Ah I think that's https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/183. Which nobody has sent a PR for yet, if you're interested! 😄 

It's an interesting point that you might not want it to create a _new_ repository - it might have been a mistype causing the repo to not be found. I edited that issue.

> If my repository is private on GitHub, I have to be a Pro user or make it public

Agreed, good point. #401 ✨

**Comment by JoshuaKGoldberg** [comment]
Closing this out as I've split out the individual pieces into their own issues. Thanks a bunch for filing @RNR1, this is very useful stuff!

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @RNR1 for bug
