### ISSUE TITLE
🐛 Bug: Setup command exit after being executed

### ISSUE THREAD

**Issue by takanome-dev** [JoshuaKGoldberg/template-typescript-node-package#403]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

I was expecting the setup script to prompt me some questions to fill out the repo, but the script exits as soon as it started.  

### Actual

```sh
Welcome to the template-typescript-node-package package setup! 🎉

│
└  Looks like there was a problem. Correct it and try again? 😕


TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at getDefaultSettings (file:///home/takanome-dev/<project-path>/template-typescript-node-package/script/setup.js:60:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/takanome-dev/<project-path>/template-typescript-node-package/script/setup.js:67:46

 ELIFECYCLE  Command failed with exit code 1.
```

### Additional Info
Steps to reproduce the error:
1. clone the repo
2. install the dependencies `pnpm install`
3. run `pnpm run setup`

---
Node version: 18.8.0
Pnpm version: 7.29.0

**Comment by JoshuaKGoldberg** [comment]
🤔 works on my machine. Perhaps the issue is with your pnpm version? Try getting the latest?

https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/9f3a7e097f3b8c87da82e8f3a9f3e8c26a42879c/package.json#L85

**Comment by takanome-dev** [comment]
Yes, it was my pnpm version :sweat_smile: 
But getting the same issue mentioned in #183 while hydrating labels. Will open a new issue.
Thanks
