### ISSUE TITLE
🐛 Bug: Setup command failed because of repository labels hydration

### ISSUE THREAD

**Issue by takanome-dev** [JoshuaKGoldberg/template-typescript-node-package#405]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Expected the script to run without any error but it failed due to some label hydration issue. Note that I'm logged in with `gh` and add my gh name when running the script.
 

### Actual

The error is `gh label edit area: documentation --color 0075ca --description Improvements or additions to docs`
For some reason it's trying to execute that in @JoshuaKGoldberg repo `HTTP 404: Not Found (https://api.github.com/repos/JoshuaKGoldberg/template-typescript-node-package/labels/area:%20documentation)` instead of mine :thinking: 

<details>
<summary>Full Stack Trace</summary>

```sh
Error: Could not hydrate repository labels. 
    at withSpinner (file:///home/takanome-dev/<project-path>/script/setup.js:178:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/takanome-dev/<project-path>/script/setup.js:417:3 {
  [cause]: Error: Command failed with exit code 1: gh label edit area: documentation --color 0075ca --description Improvements or additions to docs
  HTTP 404: Not Found (https://api.github.com/repos/JoshuaKGoldberg/template-typescript-node-package/labels/area:%20documentation)
      at makeError (file:///home/takanome-dev/<project-path>/node_modules/.pnpm/execa@7.1.1/node_modules/execa/lib/error.js:59:11)
      at handlePromise (file:///home/takanome-dev/<project-path>/node_modules/.pnpm/execa@7.1.1/node_modules/execa/index.js:124:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async withSpinner.startText (file:///home/takanome-dev/<project-path>/script/setup.js:431:6)
      at async withSpinner (file:///home/ttakanome-dev/<project-path>/script/setup.js:172:4)
      at async file:///home/takanome-dev/<project-path>/script/setup.js:417:3 {
    shortMessage: 'Command failed with exit code 1: gh label edit area: documentation --color 0075ca --description Improvements or additions to docs',
    command: 'gh label edit area: documentation --color 0075ca --description Improvements or additions to docs',
    escapedCommand: 'gh label edit "area: documentation" --color 0075ca --description "Improvements or additions to docs"',
    exitCode: 1,
    signal: undefined,
    signalDescription: undefined,
    stdout: '',
    stderr: 'HTTP 404: Not Found (https://api.github.com/repos/JoshuaKGoldberg/template-typescript-node-package/labels/area:%20documentation)',
    failed: true,
    timedOut: false,
    isCanceled: false,
    killed: false
  }
}

 ELIFECYCLE  Command failed with exit code 1.
```

</details>

**Comment by JoshuaKGoldberg** [comment]
Just making sure @takanome-dev - what are the inputs to `pnpm run setup` you're running with? The owner, repository, etc?

**Comment by takanome-dev** [comment]
Sorry for this @JoshuaKGoldberg, the issue is that I ran the script with the clone I made directly in your repo, so `origin` was `git@git.../JoshuaKGoldberg/template-typescript-node-package`. That's why there was a hydration error.

But I can't get it working with my forked repo :thinking: 


https://user-images.githubusercontent.com/79809121/236397378-0fbb33e1-4823-49fe-b59d-b81bf874b759.mp4

Maybe we should reopen #403?

**Comment by JoshuaKGoldberg** [comment]
Hmm, I think this might be better now that #411 is merged. Could you try again?

**Comment by takanome-dev** [comment]
Sorry for the delay @JoshuaKGoldberg. I have pulled the latest changes, and installed node v18.16.0 and pnpm v8.6.0 but I'm getting a different error message:

```bash
Error: Could not match a fetch remote from git.
    at getDefaultSettings (/home/takanome_dev/<project_path>/src/shared/defaults.ts:28:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getInputValuesAndOctokit (/home/takanome_dev/<project_path>/src/shared/inputs.ts:47:46)
    at runOrRestore (/home/takanome_dev/<project_path>/src/shared/runOrRestore.ts:42:31)
    at setup (/home/takanome_dev/<project_path>/src/setup/setup.ts:5:9)
    at <anonymous> (/home/takanome_dev/<project_path>/src/setup/index.ts:3:20)
```

Am I the only one facing this issue? 😅

Will try it again on Windows and report back.

**Comment by hamez0r** [comment]
I have the same problem, did you manage to find a solution?

**Comment by JoshuaKGoldberg** [comment]
Yeah I think this is, somewhat coincidentally, essentially what #518 is talking about. `getDefaultSettings` really shouldn't be throwing an error - it should just be suggesting defaults as suggested.

Closing this issue as a duplicate (since #518 is more specific). Thanks y'all!
