### ISSUE TITLE
Run eslint —fix on pre-commit with lint-staged?

### ISSUE THREAD

**Issue by MrHBS** [JoshuaKGoldberg/template-typescript-node-package#438]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Thoughts on running eslint —fix on pre-commit with lint-staged?

**Comment by JoshuaKGoldberg** [comment]
I do have thoughts 😄 and they're not very positive. tl;dr: I don't think it's a good idea, but you can always add it on if you want.

My main problem with running `eslint --fix` as a commit hook is that it can take a long time for performance. Many developers -myself included- find it annoying to have to wait for Git operations such as `commit` or `push`. Especially when you add [typescript-eslint's typed rules](https://typescript-eslint.io/linting/typed-linting): those cause linting to take up time including building up a type checker's understanding of code.

This template does include a `lint.yml` workflow to run in CI. PRs that contain ESLint complaints will have their builds failed on them.

If you _really_ want to add in linting to a Git hook, nothing stops you from doing so in your usage of this template. But I don't intend on adding it to the template itself.

Thanks for asking!
