### ISSUE TITLE
🚀 Feature: Add ":(" to the end of type: bug label description

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#454]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

This repo's setup script fills in a repository's labels with an assortment of known good labels, with preset names, descriptions, and colors.

Right now the `type: bug` label has this description:

> ```
> Something isn't working
> ```

...that's kind of boring and plain. Let's add a `:(` to the end 😄:

> ```
> Something isn't working :(
> ```

### Additional Info

Labels are stored in this `labels.json` file: https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/d95fdf1e7dc9cd0646d28ae6095c1e463a8d6d11/script/labels.json

Testing the setup script is documented in _`.github/DEVELOPMENT.md`_: https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/d95fdf1e7dc9cd0646d28ae6095c1e463a8d6d11/.github/DEVELOPMENT.md#the-setup-script

**Comment by tungbq** [comment]
Hi, I'd like to work on this issue. May I pick up this?

**Comment by JoshuaKGoldberg** [comment]
Absolutely, that'd be great - go ahead @tungbq!
