### ISSUE TITLE
🛠 Tooling: Add publishConfig.provenance = true to package.json

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#465]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

From https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/461#discussion_r1199763882: we'll want to add `publishConfig.provenance = true` to `package.json`. This will indicate for published npm packages to use [package provenance](), which is a new and important security practice.

```json
"publishConfig": {
  "provenance": true
},
```

### Additional Info

https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools

Note that I don't think we'll also want to set `publishConfig.access`, as we don't want private repos to accidentally get set to public.

**Comment by promise-dash** [comment]
Hey, I would like to resolve this.
Could you please assign me this issue?

**Comment by JoshuaKGoldberg** [comment]
We don't have assignments in this repository, go ahead and send a PR. 🙂 thanks!
