### ISSUE TITLE
🚀 Feature: Hydration should try npm and git config for email

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#499]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, when running the _hydration_ script, if an email address isn't provided with `--email`, a fallback from the existing `package.json` `"author"` is tried:

https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/6a0d42d7f07e3a70c7b0dd239c7431c58f43bd69/src/hydrate/values/getHydrationDefaults.ts#L29-L32

However, not all packages include an email in their author. Some just provide it as a string like `"author": "Josh Goldberg"`. 

In this case, it'd be nice to try, in order:
1. The user's npm account (re-using logic from `getNpmAuthor.ts`
2. The user's Git config (`git config --get user.email`)

### Additional Info

Hydration is explained here: https://github.com/JoshuaKGoldberg/template-typescript-node-package/tree/6a0d42d7f07e3a70c7b0dd239c7431c58f43bd69#repository-hydration

**Comment by RNR1** [comment]
On it
