### ISSUE TITLE
🐛 Bug: Two release comment in PRs

### ISSUE THREAD

**Issue by navin-moorthy** [JoshuaKGoldberg/template-typescript-node-package#533]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Single release comment in PR using https://github.com/apexskier/github-release-commenter like this https://github.com/apexskier/github-release-commenter/pull/179#issuecomment-846418924

### Actual

Two release comment in PR https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/519#issuecomment-1589852554 & https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/519#issuecomment-1589852453

### Additional Info

https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/7793c61cf363a689c0e902159483e8e2252cf6bd/.github/workflows/post-release.yml#L24-L28

I think the issue is because of having two invocations
1. on github release published
2. on github action `post-release` workflow dispatch

So, removing this line here https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/7793c61cf363a689c0e902159483e8e2252cf6bd/.github/workflows/release.yml#L38 or here https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/7793c61cf363a689c0e902159483e8e2252cf6bd/.github/workflows/post-release.yml#L25-L27 should fix the issue IMO.

Context: https://github.com/apexskier/github-release-commenter/issues/433

**Comment by JoshuaKGoldberg** [comment]
Oh! Thank you, that makes a lot of sense 😄. I'll try it out now & mark you as a co-author.

**Comment by JoshuaKGoldberg** [comment]
Nice, you were right! Thanks!
