### ISSUE TITLE
🛠 Tooling: Add cancel-in-progress to release job

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#556]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, `release.yml` -the workflow job that releases new versions of the package upon commits to the `main` branch- is set to never cancel in-progress releases workflows:

https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/d4b1c7950e8cb8886eb98aff4223079b343936a8/.github/workflows/release.yml#L1-L2

In other words: if there are two commits merged to the `main` branch quickly, they'll both have the `release` workflow run on them, in series. The second commit's workflow will wait until the first one's is done.

However, the first commit's workflow will always fail if it's behind the `main` branch in terms of commits! Example from https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/5292082143/jobs/9578516799:

```plaintext
Changeset:
 M package.json
ERROR To https://github.com/JoshuaKGoldberg/template-typescript-node-package
 * [new tag]         v1.28.25 -> v1.28.25
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/JoshuaKGoldberg/template-typescript-node-package'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Rolling back changes...
```

So, I think we should change the workflow to `cancel-in-progress: true`. That way, when there are multiple quick commits, on the last one's release workflow will run. And it'll release a new version with each commit's changes.

Accepting PRs to make this one line change 😄. Leaving it open as a `good first issue` as it's not time-sensitive. 

### Additional Info

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency explains concurrency.

**Comment by Jolg42** [comment]
I opened a small PR https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/568 😉
