### ISSUE TITLE
🛠 Tooling: consider `lint-staged` for local precommit hook linting

### ISSUE THREAD

**Issue by Pinjasaur** [JoshuaKGoldberg/template-typescript-node-package#68]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue+label%3A%22area%3A+tooling%22) and found none that matched my issue.

### Overview

Breaking out of discussion in #66.

Consider using `lint-staged` to apply linting rules to _staged_ (e.g. changed) files locally via a precommit hook.

[tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config) was the recommendation to benchmark against. The initial concern being ESLint + type info could cause slowness.

**Comment by nowyDEV** [comment]
I've ran a quick benchmarks:

### tslint-to-eslint-config

![tslint-to-eslint-config-eslint-benchmark](https://user-images.githubusercontent.com/12304307/222237112-6918b584-6dd0-4315-a276-f3f90c93527f.png)

When running pre-commit hook on 35 staged files, it takes around 5 seconds to complete (including autof-fixing a few files).

### template-typescript-node-package

![template-typescript-node-package-benchmark](https://user-images.githubusercontent.com/12304307/222237386-999e8e93-4c3c-40d9-a0fd-7f7a7f72a4a8.png)

When running pre-commit hook on 5 staged files, it takes around 5 seconds to complete(i assume most of the time here is spent on initializing the check and the check itself is super-fast).

From the personal experience, I've had some issues with eslint performance in a middle-sized codebases (30-60k LOC).
In one of them I had to disable some slow rules(most of them were relying on type information as expected).
https://github.com/nordcloud/eslint-config-pat/blob/master/profile/_common.js#L80

```json
// Disable performance-costly rules that increase time of eslint action, they cause git hooks to run very slow
...(isGitHook && {
  "@typescript-eslint/no-misused-promises": "off",
  "@typescript-eslint/no-unsafe-assignment": "off",
  "import/no-deprecated": "off",
}),
```

Git hook with eslint enabled takes around 10-15s on projects this size, take into consideration that there are more plugins there (for react, testing-library, graphql).

**Comment by JoshuaKGoldberg** [comment]
Oof, multiple seconds in a Git hook! That's unfortunate. 

I'm going to close this as resolved & wontfixed. Thanks for the investigation @nowyDEV!

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @nowyDEV for tool
