### ISSUE TITLE
🛠 Tooling: Move "plugin:typescript-sort-keys/recommended" from global scope of eslintrc to override scope for "**/*.{ts,tsx}" files.

### ISSUE THREAD

**Issue by NazCodeland** [JoshuaKGoldberg/template-typescript-node-package#69]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue+label%3A%22area%3A+tooling%22) and found none that matched my issue.

### Overview

The "plugin:typescript-sort-keys/recommended", should be listed in the "extends" key in the "overrides" key for the files "**/*.{ts,tsx}".

**Comment by JoshuaKGoldberg** [comment]
Yip yip, makes sense - thanks for pointing this out!
